// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import jwt "github.com/dgrijalva/jwt-go"
import mock "github.com/stretchr/testify/mock"

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

// CheckJWT provides a mock function with given fields: tokenStr
func (_m *AuthService) CheckJWT(tokenStr string) (*jwt.Token, error) {
	ret := _m.Called(tokenStr)

	var r0 *jwt.Token
	if rf, ok := ret.Get(0).(func(string) *jwt.Token); ok {
		r0 = rf(tokenStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt.Token)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenStr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
